import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');

test('JSON and catalog overwrite MDX regardless of its previous origin', (t) => {
  const temp = fs.mkdtempSync(path.join(os.tmpdir(), 'ze-map-entries-'));
  t.after(() => fs.rmSync(temp, { recursive: true, force: true }));
  for (const dir of ['scripts/content', 'shared', 'data/research', 'src/content/maps', 'public/entity']) {
    fs.mkdirSync(path.join(temp, dir), { recursive: true });
  }
  fs.copyFileSync(path.join(root, 'scripts/content/generate-map-entries.mjs'), path.join(temp, 'scripts/content/generate-map-entries.mjs'));
  fs.copyFileSync(path.join(root, 'shared/difficulty.mjs'), path.join(temp, 'shared/difficulty.mjs'));
  fs.writeFileSync(path.join(temp, 'package.json'), '{"type":"module"}');
  fs.writeFileSync(path.join(temp, 'scripts/content/curated-links.json'), JSON.stringify({
    ze_rich: { primary: 'ze_other', versions: ['ze_other'] },
  }));
  fs.writeFileSync(path.join(temp, 'public/entity/catalog.json'), JSON.stringify({
    meta: { legacyBuilt: '2026-01-01' }, groups: [], maps: [
      { a: '2001', m: 'ze_demo', s: '2001-ze_demo-1', f: '1', k: '2001/ze_demo/1', cn: 'Demo', n: 1, k2: 1, st: 0, c: {}, t: [] },
      { a: '2001', m: 'ze_other', s: '2001-ze_other-2', f: '2', k: '2001/ze_other/2', cn: 'Other', n: 1, k2: 1, st: 0, c: {}, t: [] },
    ],
  }));
  fs.writeFileSync(path.join(temp, 'data/research/ze_demo.json'), JSON.stringify({ title: 'From JSON', summary: null, tags: [] }));
  const rich = '---\ntitle: Rich\ntitleEn: ze_rich\ngame: CS2\ndifficulty: 未知\nstages: 0\ntags: []\n---\n{/* generated by scripts/content/generate-map-entries.mjs */}\nRich body\n';
  fs.writeFileSync(path.join(temp, 'data/research/ze_rich.json'), JSON.stringify({ document: rich }));
  fs.writeFileSync(path.join(temp, 'src/content/maps/ze_demo.mdx'), 'Manual MDX without generator marker');
  fs.writeFileSync(path.join(temp, 'src/content/maps/ze_rich.mdx'), 'Old manual rich page');

  const generate = () => {
    const result = spawnSync(process.execPath, [path.join(temp, 'scripts/content/generate-map-entries.mjs')], { encoding: 'utf8' });
    assert.equal(result.status, 0, result.stderr);
  };
  generate();
  const demo = fs.readFileSync(path.join(temp, 'src/content/maps/ze_demo.mdx'), 'utf8');
  assert.match(demo, /title: "From JSON"/);
  assert.doesNotMatch(demo, /Manual MDX/);
  assert.equal(fs.readFileSync(path.join(temp, 'src/content/maps/ze_rich.mdx'), 'utf8'), rich);
  generate();
  assert.equal(fs.readFileSync(path.join(temp, 'src/content/maps/ze_demo.mdx'), 'utf8'), demo);
});
